-- Sample marketing and e-commerce schema for text-to-sql-agent.
-- Written to run unchanged on SQLite and PostgreSQL.
-- All rows are synthetic, generated by db/seed.py from a fixed random seed.

CREATE TABLE customers (
    id          INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    email       TEXT NOT NULL UNIQUE,
    country     TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE products (
    id          INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    category    TEXT NOT NULL,
    unit_price  NUMERIC(10, 2) NOT NULL
);

CREATE TABLE campaigns (
    id          INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    platform    TEXT NOT NULL CHECK (platform IN ('google', 'meta')),
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    budget      NUMERIC(10, 2) NOT NULL
);

-- session_id is the click-to-order attribution key. An order whose session_id
-- matches an ad click is attributed to that click's campaign. Each click has
-- its own session, so the join from orders to ad_clicks is one to one.
CREATE TABLE ad_clicks (
    id            INTEGER PRIMARY KEY,
    campaign_id   INTEGER NOT NULL REFERENCES campaigns(id),
    session_id    TEXT NOT NULL UNIQUE,
    clicked_at    TIMESTAMP NOT NULL,
    landing_page  TEXT NOT NULL
);

CREATE TABLE orders (
    id            INTEGER PRIMARY KEY,
    customer_id   INTEGER NOT NULL REFERENCES customers(id),
    -- Matches ad_clicks.session_id when the order came from a tracked ad click,
    -- NULL otherwise.
    session_id    TEXT,
    order_date    DATE NOT NULL,
    status        TEXT NOT NULL CHECK (status IN ('paid', 'pending', 'refunded')),
    total_amount  NUMERIC(10, 2) NOT NULL
);

CREATE TABLE order_items (
    id          INTEGER PRIMARY KEY,
    order_id    INTEGER NOT NULL REFERENCES orders(id),
    product_id  INTEGER NOT NULL REFERENCES products(id),
    quantity    INTEGER NOT NULL,
    unit_price  NUMERIC(10, 2) NOT NULL
);

CREATE TABLE payments (
    id        INTEGER PRIMARY KEY,
    order_id  INTEGER NOT NULL REFERENCES orders(id),
    amount    NUMERIC(10, 2) NOT NULL,
    method    TEXT NOT NULL,
    paid_at   TIMESTAMP NOT NULL,
    status    TEXT NOT NULL
);

CREATE INDEX idx_ad_clicks_campaign_id ON ad_clicks(campaign_id);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_session_id ON orders(session_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_payments_order_id ON payments(order_id);
